# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Kerim's Micro Blog"
tagline: ""
description: "Follow <a href=\"https://micro.blog/kerim\">@kerim on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/kerim\">@kerim on Micro.blog</a>."
baseurl: ""
url: "https://micro.oxus.net"
markdown: "kramdown"
username: "kerim"
microblog_user: "kerim"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Kerim's Micro Blog"
name: "Kerim's Micro Blog"
gravatar_hash: "3f733bd06413af380fcd122e4be08dc4"
avatar: "https://micro.blog/kerim/avatar.jpg"
full_name: "Kerim's Micro Blog"
bio: ""
twitter_username: "kerim"
github_username: "kerim"
instagram_username: "kerimfriedman"
paginate: 20
paginate_path: "/page/:num/"
timezone: "Singapore"
site_id: "2872"
gems: ["jekyll-paginate"]
itunes_description: "Kerim Friedman is an anthropologist, blogger, and filmmaker. Read more about Kerim on his [homepage](https://kerim.oxus.net)."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Kerim Friedman"
itunes_email: ""
podcast: false